Fixes. backup and unison now work on foreign remotes.

diff --git a/lib/commands/backup b/lib/commands/backup
--- a/lib/commands/backup
+++ b/lib/commands/backup
@@ -44,26 +44,38 @@ backup_cleanup() {
   require settings
   unset BACKUP_DIR
   unset BACKUP_LIST
+  crontask del backup hourly
+  crontask del backup daily
+  crontask del backup weekly
   settings save
 }
 
 backup_add() {
-  local host="$1"; shift
+  local entry="$1"; shift
   local period="$1"; shift || period="daily"
   require settings
   require sshlink
+  require backup setup
+
+  local host="${entry%%:*}"
 
   sshlink add "$host"
+  if [ "$host" != "$entry" ] && ! sshlink check_sc "$host"; then
+    echo "Error: $SC is not installed on $host"
+    exit 1
+  fi
 
-  BACKUP_LIST="$BACKUP_LIST ${period}_$host "
+  BACKUP_LIST="$BACKUP_LIST${period}:$entry "
 
   settings save
 }
 
 backup_del() {
+  local entry="$1"; shift
+  local period="$1"; shift || period="daily"
   require settings
 
-  BACKUP_LIST="$(sed -e "s/ $period_$host //" <<< "$BACKUP_LIST")"
+  BACKUP_LIST="$(sed -e "s/$period:$entry //" <<< "$BACKUP_LIST")"
 
   settings save
 }
@@ -71,37 +83,45 @@ backup_del() {
 backup_cron() {
   local period="$1"; shift
 
-  local bhost
+  local bentry
   local bperiod
-  local bdblist
-  local bdb
-  local bdbuser
-  local bdbname
   for b in $BACKUP_LIST; do
-    bperiod="${b%%_*}"
-    bhost="${b#*_}"
+    bperiod="${b%%:*}"
+    bentry="${b#*:}"
     [ "$bperiod" = "$period" ] || continue
 
-    backup start "$bhost"
+    backup start "$bentry"
   done
 }
 
 backup_start() {
-  local bhost="$1"; shift
-
-  [ -d "$BACKUP_DIR/$bhost/fs" ] || mkdir -p "$BACKUP_DIR/$bhost/fs"
+  local entry="$1"; shift
+  local host="${entry%%:*}"
   require sshlink
-  sshlink sc "$bhost" broadcall files | sshlink getfiles "$bhost" "$BACKUP_DIR/$bhost/fs"
 
-  bdblist="$(sshlink sc "$bhost" broadcall db)"
-  if [ "$bdblist" ]; then
-    require db
-    [ -d "$BACKUP_DIR/$bhost/db" ] || mkdir -p "$BACKUP_DIR/$bhost/db"
-    for bdb in $bdblist; do
-      bdbuser="${bdb%%:*}"
-      bdbname="${bdb#*:}"
-      sshlink sc "$bhost" db backup "$bdbuser" "$bdbname" > "$BACKUP_DIR/$bhost/db/$bdb.xz"
-    done
+  [ -d "$BACKUP_DIR/$host/fs" ] || mkdir -p "$BACKUP_DIR/$host/fs"
+
+  if [ "$host" != "$entry" ]; then
+    # Backup a SC compatible host
+    sshlink sc "$host" broadcall files | sshlink getfiles "$bost" "$BACKUP_DIR/$host/fs"
+    local dblist="$(sshlink sc "$host" broadcall db)"
+
+    if [ "$dblist" ]; then
+      require db
+      local db
+      local dbuser
+      local dbname
+      [ -d "$BACKUP_DIR/$host/db" ] || mkdir -p "$BACKUP_DIR/$host/db"
+      for db in $bdblist; do
+        dbuser="${db%%:*}"
+        dbname="${db#*:}"
+        sshlink sc "$host" db backup "$dbuser" "$dbname" > "$BACKUP_DIR/$host/db/$db.xz"
+      done
+    fi
+  else
+    # Backup a specific path on a foreign host
+    local path="${entry#*:}"
+    sshlink getfiles "$host" "$DIRBACKUP_ROOT/$host/fs" <<< "$path"
   fi
 }
 
@@ -121,7 +141,12 @@ backup_enabled() {
 }
 
 backup_ready() {
-  if backup enabled; then
+  if backup enabled \
+  && has crontask \
+  && crontask has backup hourly \
+  && crontask has backup daily \
+  && crontask has backup weekly \
+  ; then
     return 0
   fi
   return 1
diff --git a/lib/commands/master b/lib/commands/master
--- a/lib/commands/master
+++ b/lib/commands/master
@@ -42,6 +42,23 @@ $SC master setup [REMOTE]
 EOF
 }
 
+master__link() {
+  require settings
+  settings prompt MASTER "" "Enter master server host"
+  if [ -z "$MASTER" ]; then
+    echo "Error: master server empty"
+    exit 1
+  fi
+  if ! sshlink has "$MASTER"; then
+    sshlink add "$MASTER"
+  fi
+  if ! sshlink check_sc "$MASTER"; then
+    echo "$SC not installed on $MASTER"
+    exit 2
+  fi
+  echo "Linked successfully to $MASTER"
+}
+
 master_setup() {
   require settings
   require sshlink
@@ -56,19 +73,7 @@ master_setup() {
     "roaming" "Remote client, synchronize only selected users"
 
   if [ "$(master mode)" != "master" ]; then
-    settings prompt MASTER "" "Enter master server user and host (empty if this host is the master):"
-    if [ -z "$MASTER" ]; then
-      echo "Error: master server empty"
-      exit 1
-    fi
-    if ! sshlink has "$MASTER"; then
-      sshlink add "$MASTER"
-    fi
-    if ! sshlink check "$MASTER"; then
-      echo "Link to $MASTER failed"
-      exit 1
-    fi
-    echo "Linked successfully to $MASTER"
+    master__link
   else
     MASTER=""
   fi
@@ -180,6 +185,7 @@ master_promote() {
     "master")
       case "$newmode" in
         "standby")
+          master__link
           require unisonsync setup
           require crontask
           crontask add master daily
@@ -236,7 +242,15 @@ master_pull() {
 
 master_cron() {
   local period="$1"; shift
-  master pull
+  case "$period" in
+    daily)
+      master pull
+      ;;
+    fast)
+      require user
+      user sync
+      ;;
+  esac
 }
 
 master_boot() {
diff --git a/lib/commands/unisonsync b/lib/commands/unisonsync
--- a/lib/commands/unisonsync
+++ b/lib/commands/unisonsync
@@ -36,16 +36,16 @@ unisonsync_setup() {
   settings save
 }
 
-unisonsync_remotesetup() {
-  if unisonsync ready; then
-    return 0
+unisonsync__remotesetup() {
+  # Setup a remote host to make sure that it is unison compatible
+  require sshlink
+  sshlink add "$host"
+  if ! sshlink exec "$host" which unison &>/dev/null; then
+    if ! sshlink exec "$host" apt install unison; then
+      echo "Error: unison not installed on remote host $host"
+      exit 2
+    fi
   fi
-
-  require settings
-  settings set UNISON "$1"
-  [ -d "$UNISON" ] || mkdir -p "$UNISON"
-
-  unisonsync setup
 }
 
 unisonsync_settings() {
@@ -70,9 +70,7 @@ root = $localpath
 root = ssh://root@$host/$remotepath
 EOF
 
-  require sshlink
-  sshlink add "$host"
-  sshlink sc "$host" unisonsync remotesetup "$UNISON"
+  unisonsync__remotesetup "$host"
 }
 
 unisonsync_has() {
