First debug WIP

diff --git a/lib/commands/master b/lib/commands/master
--- a/lib/commands/master
+++ b/lib/commands/master
@@ -45,6 +45,7 @@ EOF
 master_setup() {
   require settings
   require sshlink
+echo XXX calling syspackage rsync rsync
   syspackage rsync rsync
 
   settings choice MASTER_MODE "standby" "Select relationship with the master server" \
@@ -56,8 +57,16 @@ master_setup() {
 
   if [ "$(master mode)" != "master" ]; then
     settings prompt MASTER "" "Enter master server user and host (empty if this host is the master):"
+    if [ -z "$MASTER" ]; then
+      echo "Error: master server empty"
+      exit 1
+    fi
     if ! sshlink has "$MASTER"; then
       sshlink add "$MASTER"
+    fi
+    if ! sshlink check "$MASTER"; then
+      echo "Link to $MASTER failed"
+      exit 1
     fi
     echo "Linked successfully to $MASTER"
   else
diff --git a/lib/common b/lib/common
--- a/lib/common
+++ b/lib/common
@@ -39,11 +39,21 @@ subcall() {
   mod="$1"; shift
   sub="$1"; shift
   if [ "$(type -t "${mod}_$sub")" = "function" ]; then
-    "${mod}_$sub"
+    "${mod}_$sub" "$@"
   else
     echo "Cannot find $SC $mod $sub"
     exit 1
   fi
+}
+
+# Tell if a submodule supports a function
+cancall() {
+  mod="$1"; shift
+  sub="$1"; shift
+  if [ "$(type -t "${mod}_$sub")" = "function" ]; then
+    return 0
+  fi
+  return 1
 }
 
 # Import a common module
@@ -148,21 +158,32 @@ optcall() {
 # Check that command-lines are available, and if some are missing, install the corresponding system package
 syspackage() {
   local package="$1"; shift
-  local commands
 
-  require apt setup
+  require aptpackage setup
 
   if [ "$#" -eq 0 ]; then
-    apt install "$package"
-    return $?
+    if apt-get -y install "$package"; then
+      return 0
+    else
+      echo "Cannot install required package $package"
+      exit 1
+    fi
+
+    return 0
   fi
 
-  for c in "${commands[@]}"; do
+  for c in "$@"; do
     if ! [ -e "$c" ] && ! which "$c" &>/dev/null; then
-      apt install "$package"
-      return $?
+      if apt-get -y install "$package"; then
+        return 0
+      else
+        echo "Cannot install required package $package"
+        exit 1
+      fi
     fi
   done
+
+  return 0
 }
 
 git_get() {
diff --git a/lib/db b/lib/db
--- a/lib/db
+++ b/lib/db
@@ -59,23 +59,45 @@ db_backup() {
   syspackage xz xz-utils
   syspackage postgresql-client pg_dump pg_dumpall
   pushd / &>/dev/null
+  echo "DROP DATABASE IF EXISTS $database;"
   echo "DROP ROLE IF EXISTS $user;"
   su -c "pg_dumpall --roles-only | grep -P '^(?:CREATE|DROP|ALTER) ROLE $user' " postgres
-  echo "DROP DATABASE IF EXISTS $database;"
   echo "CREATE DATABASE $database OWNER=$user;"
   su -c "pg_dump --no-tablespaces $database | xz -c -6" postgres
   popd &>/dev/null
 }
 
 # Restores a xz backup from stdin into the local postgres
-db_restore() {
-  local database="$1"; shift
+db_restorestream() {
+  local database="$1"; shift || database=postgres
 
   syspackage unxz xz-utils
   syspackage postgresql-client psql
   pushd / &>/dev/null
-  su -c 'unxz -c | psql -q $database' postgres >/dev/null
+  su -c "unxz -c | psql -q $database" postgres >/dev/null
   popd &>/dev/null
+}
+
+db_restoremodule() {
+  local module="$1"; shift
+  local source="$1"; shift
+
+  require "$module"
+
+  # Check if the module has a db
+  if ! cancall "$module" db; then return 0; fi
+
+  local dbname
+  local dbfile
+  for dbname in "$("$module" db)"; do
+    dbfile="$source/db/$dbname.xz"
+    if [ -e "$dbfile" ]; then
+      db restorestream < "$dbfile"
+    else
+      echo "Error: Backup of database $dbname missing"
+      exit 2
+    fi
+  done
 }
 
 db_add() {
